export const COUNTRIES = [
  { name: "Австралия", slug: "Avstraliya" },
  { name: "Бразилия", slug: "Braziliya" },
  { name: "Великобритания", slug: "Velikobritaniya" },
  { name: "Германия", slug: "Germaniya" },
  { name: "Гонконг", slug: "Gonkong" },
  { name: "Индия", slug: "Indiya" },
  { name: "Испания", slug: "Ispaniya" },
  { name: "Италия", slug: "Italiya" },
  { name: "Канада", slug: "Kanada" },
  { name: "Китай", slug: "Kitay" },
  { name: "Корея Южная", slug: "Koreya-Yuzhnaya" },
  { name: "Мексика", slug: "Meksika" },
  { name: "Россия", slug: "Rossiya" },
  { name: "СССР", slug: "SSSR" },
  { name: "США", slug: "SShA" },
  { name: "Турция", slug: "Turciya" },
  { name: "Франция", slug: "Franciya" },
  { name: "Япония", slug: "Yaponiya" },
] as const

export const GENRES = [
  { name: "аниме", slug: "anime" },
  { name: "биография", slug: "biografiya" },
  { name: "боевик", slug: "boevik" },
  { name: "вестерн", slug: "vestern" },
  { name: "военный", slug: "voennyy" },
  { name: "детектив", slug: "detektiv" },
  { name: "детский", slug: "detskiy" },
  { name: "для взрослых", slug: "dlya-vzroslyh" },
  { name: "документальный", slug: "dokumentalnyy" },
  { name: "драма", slug: "drama" },
  { name: "игра", slug: "igra" },
  { name: "история", slug: "istoriya" },
  { name: "комедия", slug: "komediya" },
  { name: "концерт", slug: "koncert" },
  { name: "короткометражка", slug: "korotkometrazhka" },
  { name: "криминал", slug: "kriminal" },
  { name: "мелодрама", slug: "melodrama" },
  { name: "музыка", slug: "muzyka" },
  { name: "мультфильм", slug: "multfilm" },
  { name: "мюзикл", slug: "myuzikl" },
  { name: "новости", slug: "novosti" },
  { name: "приключения", slug: "priklyucheniya" },
  { name: "реальное ТВ", slug: "realnoe-TV" },
  { name: "семейный", slug: "semeynyy" },
  { name: "спорт", slug: "sport" },
  { name: "ток-шоу", slug: "tok-shou" },
  { name: "триллер", slug: "triller" },
  { name: "ужасы", slug: "uzhasy" },
  { name: "фантастика", slug: "fantastika" },
  { name: "фильм-нуар", slug: "film-nuar" },
  { name: "фэнтези", slug: "fentezi" },
  { name: "церемония", slug: "ceremoniya" },
] as const
